In [1]:
import polars as pl
import pandas as pd

In [2]:
ddal_df = pl.read_parquet("../data/dis2vec_all_preds.parquet.gzip")

ddal_df

shape: (11_094_404, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ pair         ┆ Dis2vec_Pre ┆ Dis2vec_Pre ┆ node1_disea ┆ node2_disea ┆ node1_disea ┆ node2_disea │
│ ---          ┆ d_mean      ┆ d_std       ┆ se_id       ┆ se_id       ┆ se_name     ┆ se_name     │
│ str          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│              ┆ f32         ┆ f32         ┆ str         ┆ str         ┆ str         ┆ str         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ ORPHA_2332__ ┆ 0.787477    ┆ 0.10573     ┆ ORPHA_2332  ┆ ORPHA_44035 ┆ KBG         ┆ Autosomal   │
│ ORPHA_440354 ┆             ┆             ┆             ┆ 4           ┆ syndrome    ┆ dominant    │
│              ┆             ┆             ┆             ┆             ┆             ┆ myopia-midf │
│              ┆             ┆             ┆             ┆             ┆             ┆ …           │
│ ORPHA_352596 ┆ 0.861128    ┆ 0.007597    ┆ ORPHA_79096 ┆ ORPHA_35259 ┆ Pyridoxal   ┆ Progressive │
│ __ORPHA_7909 ┆             ┆             ┆             ┆ 6           ┆ phosphate-r ┆ myoclonic   │
│ 6            ┆             ┆             ┆             ┆             ┆ esponsive…  ┆ epilepsy…   │
│ ORPHA_71529_ ┆ 0.000394    ┆ 0.00029     ┆ ORPHA_93267 ┆ ORPHA_71529 ┆ Cloverleaf  ┆ Obesity due │
│ _ORPHA_93267 ┆             ┆             ┆             ┆             ┆ skull-multi ┆ to melanoco │
│              ┆             ┆             ┆             ┆             ┆ ple cong…   ┆ rtin 4 …    │
│ ORPHA_100974 ┆ 0.170978    ┆ 0.033091    ┆ ORPHA_79478 ┆ ORPHA_10097 ┆ Griscelli   ┆ FRAXF       │
│ __ORPHA_7947 ┆             ┆             ┆             ┆ 4           ┆ syndrome    ┆ syndrome    │
│ 8            ┆             ┆             ┆             ┆             ┆ type 3      ┆             │
│ ORPHA_1657__ ┆ 0.719929    ┆ 0.147701    ┆ ORPHA_1657  ┆ ORPHA_90307 ┆ Dermatooste ┆ Parkes      │
│ ORPHA_90307  ┆             ┆             ┆             ┆             ┆ olysis,     ┆ Weber       │
│              ┆             ┆             ┆             ┆             ┆ Kirghizian  ┆ syndrome    │
│              ┆             ┆             ┆             ┆             ┆ …           ┆             │
│ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           │
│ ORPHA_279882 ┆ 0.002016    ┆ 0.000189    ┆ ORPHA_27988 ┆ ORPHA_90342 ┆ Spasmus     ┆ Xeroderma   │
│ __ORPHA_9034 ┆             ┆             ┆ 2           ┆             ┆ nutans      ┆ pigmentosum │
│ 2            ┆             ┆             ┆             ┆             ┆             ┆ variant     │
│ ORPHA_178464 ┆ 0.007933    ┆ 0.002401    ┆ ORPHA_17846 ┆ ORPHA_71493 ┆ Hereditary  ┆ Familial    │
│ __ORPHA_7149 ┆             ┆             ┆ 4           ┆             ┆ myopathy    ┆ thrombocyto │
│ 3            ┆             ┆             ┆             ┆             ┆ with early… ┆ sis         │
│ EFO_0000274_ ┆ 0.001939    ┆ 0.000581    ┆ ORPHA_35329 ┆ EFO_0000274 ┆ Roifman     ┆ atopic      │
│ _ORPHA_35329 ┆             ┆             ┆ 8           ┆             ┆ syndrome    ┆ eczema      │
│ 8            ┆             ┆             ┆             ┆             ┆             ┆             │
│ ORPHA_163934 ┆ 0.033205    ┆ 0.010691    ┆ ORPHA_16393 ┆ ORPHA_3463  ┆ Atopic kera ┆ Wolfram     │
│ __ORPHA_3463 ┆             ┆             ┆ 4           ┆             ┆ toconjuncti ┆ syndrome    │
│              ┆             ┆             ┆             ┆             ┆ vitis       ┆             │
│ ORPHA_1790__ ┆ 0.000403    ┆ 0.00001     ┆ ORPHA_1790  ┆ ORPHA_26351 ┆ Hypomandibu ┆ Progressive │
│ ORPHA_263516 ┆             ┆             ┆             ┆ 6           ┆ lar faciocr ┆ myoclonic   │
│              ┆             ┆             ┆             ┆             ┆ anial dy…   ┆ epilepsy…   │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [18]:
dis2vec_clust_df = pd.read_excel("../data/dis2vec_clust.xlsx", index_col=0)

In [27]:
# Find disease IDs

dis2vec_clust_df[dis2vec_clust_df['name'].str.contains('Overlap Myositis', case=False, na=False)]

,node,dis_vec,disease_id,name,dis_vec_clust,PCA,UMAP,x,y,clust lbl,rare
2796,2796,[ 1.2237573e-01 -2.0220878e-03 -1.4460491e-01 ...,ORPHA_206572,Overlap myositis,38,[ 1.08692023 -0.05673184],[4.1278257 2.150249 ],4.127826,2.150249,clust 38,rare

In [20]:
# aHUS -- PNH
ddal_df.filter(pl.col('pair').is_in(['ORPHA_2134__ORPHA_447']))

shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ pair         ┆ Dis2vec_Pre ┆ Dis2vec_Pre ┆ node1_disea ┆ node2_disea ┆ node1_disea ┆ node2_disea │
│ ---          ┆ d_mean      ┆ d_std       ┆ se_id       ┆ se_id       ┆ se_name     ┆ se_name     │
│ str          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│              ┆ f32         ┆ f32         ┆ str         ┆ str         ┆ str         ┆ str         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ ORPHA_2134__ ┆ 0.993673    ┆ 0.001072    ┆ ORPHA_2134  ┆ ORPHA_447   ┆ Atypical    ┆ Paroxysmal  │
│ ORPHA_447    ┆             ┆             ┆             ┆             ┆ hemolytic   ┆ nocturnal   │
│              ┆             ┆             ┆             ┆             ┆ uremic      ┆ hemoglobi…  │
│              ┆             ┆             ┆             ┆             ┆ synd…       ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [ ]:
# RA -- Antisynthetase syndrome
ddal_df.filter(pl.col('pair').is_in(['EFO_0000685__ORPHA_81']))

shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ pair         ┆ Dis2vec_Pre ┆ Dis2vec_Pre ┆ node1_disea ┆ node2_disea ┆ node1_disea ┆ node2_disea │
│ ---          ┆ d_mean      ┆ d_std       ┆ se_id       ┆ se_id       ┆ se_name     ┆ se_name     │
│ str          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│              ┆ f32         ┆ f32         ┆ str         ┆ str         ┆ str         ┆ str         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ EFO_0000685_ ┆ 0.983776    ┆ 0.005973    ┆ EFO_0000685 ┆ ORPHA_81    ┆ rheumatoid  ┆ Antisynthet │
│ _ORPHA_81    ┆             ┆             ┆             ┆             ┆ arthritis   ┆ ase         │
│              ┆             ┆             ┆             ┆             ┆             ┆ syndrome    │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [21]:
# RA -- Polymyositis
ddal_df.filter(pl.col('pair').is_in(['EFO_0000685__ORPHA_732']))

shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ pair         ┆ Dis2vec_Pre ┆ Dis2vec_Pre ┆ node1_disea ┆ node2_disea ┆ node1_disea ┆ node2_disea │
│ ---          ┆ d_mean      ┆ d_std       ┆ se_id       ┆ se_id       ┆ se_name     ┆ se_name     │
│ str          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│              ┆ f32         ┆ f32         ┆ str         ┆ str         ┆ str         ┆ str         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ EFO_0000685_ ┆ 0.930126    ┆ 0.014539    ┆ EFO_0000685 ┆ ORPHA_732   ┆ rheumatoid  ┆ Polymyositi │
│ _ORPHA_732   ┆             ┆             ┆             ┆             ┆ arthritis   ┆ s           │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [ ]:
# RA -- Dermatomyositis
ddal_df.filter(pl.col('pair').is_in(['EFO_0000685__ORPHA_645613']))

shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ pair         ┆ Dis2vec_Pre ┆ Dis2vec_Pre ┆ node1_disea ┆ node2_disea ┆ node1_disea ┆ node2_disea │
│ ---          ┆ d_mean      ┆ d_std       ┆ se_id       ┆ se_id       ┆ se_name     ┆ se_name     │
│ str          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│              ┆ f32         ┆ f32         ┆ str         ┆ str         ┆ str         ┆ str         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ EFO_0000685_ ┆ 0.949287    ┆ 0.020564    ┆ EFO_0000685 ┆ ORPHA_64561 ┆ rheumatoid  ┆ Classical   │
│ _ORPHA_64561 ┆             ┆             ┆             ┆ 3           ┆ arthritis   ┆ dermatomyos │
│ 3            ┆             ┆             ┆             ┆             ┆             ┆ itis        │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [ ]:
# RA -- Mixed connective tissue disease
ddal_df.filter(pl.col('pair').is_in(['EFO_0000685__ORPHA_809']))

shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ pair         ┆ Dis2vec_Pre ┆ Dis2vec_Pre ┆ node1_disea ┆ node2_disea ┆ node1_disea ┆ node2_disea │
│ ---          ┆ d_mean      ┆ d_std       ┆ se_id       ┆ se_id       ┆ se_name     ┆ se_name     │
│ str          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│              ┆ f32         ┆ f32         ┆ str         ┆ str         ┆ str         ┆ str         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ EFO_0000685_ ┆ 0.982725    ┆ 0.000896    ┆ EFO_0000685 ┆ ORPHA_809   ┆ rheumatoid  ┆ Mixed       │
│ _ORPHA_809   ┆             ┆             ┆             ┆             ┆ arthritis   ┆ connective  │
│              ┆             ┆             ┆             ┆             ┆             ┆ tissue      │
│              ┆             ┆             ┆             ┆             ┆             ┆ diseas…     │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [29]:
# RA -- Overlap myositis
ddal_df.filter(pl.col('pair').is_in(['EFO_0000685__ORPHA_206572']))

shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ pair         ┆ Dis2vec_Pre ┆ Dis2vec_Pre ┆ node1_disea ┆ node2_disea ┆ node1_disea ┆ node2_disea │
│ ---          ┆ d_mean      ┆ d_std       ┆ se_id       ┆ se_id       ┆ se_name     ┆ se_name     │
│ str          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│              ┆ f32         ┆ f32         ┆ str         ┆ str         ┆ str         ┆ str         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ EFO_0000685_ ┆ 0.972003    ┆ 0.006891    ┆ EFO_0000685 ┆ ORPHA_20657 ┆ rheumatoid  ┆ Overlap     │
│ _ORPHA_20657 ┆             ┆             ┆             ┆ 2           ┆ arthritis   ┆ myositis    │
│ 2            ┆             ┆             ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘